<h1 style="color:red">One Hot Encoding</h1>

In [43]:
import pandas as pd 
import numpy as np

In [44]:
df = pd.read_csv("cars.csv")
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
7285    Maruti      70195  Diesel  Second Owner         434999
170      Volvo      30000  Petrol   First Owner       10000000
6629  Mahindra      80000  Diesel   First Owner         722000
44      Maruti      23300  Petrol   First Owner         675000
7798      Tata      78000  Diesel  Second Owner         525000

In [45]:
df['brand'].value_counts()       
# we can see more cars of some brands are there(quite frequent), while some brands are very few in numbers.

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [46]:
print("No. of unique brands :", df['brand'].nunique())

No. of unique brands : 32

In [47]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [48]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

<h2 style="color:blue">OneHotEncoding using pandas</h2>

Multicollinearity: - If any mathematical relationship exists b/w Input columns, all I/p columns are dependent to each other.
In ML,       Input columns  ->  Independent from each other
             and Output/target column  -> dependent colum

as we can see  Σ (I/p columns of a row) = 1

This indicates dependency of I/p columns and is quite disturbing for Linear Models (Linear Regression, Logistic Regression)

so generally we Remove first column
X columns  → (X-1) columns

Colors       yellow   red  blue                   red  blue          
yellow          1      0     0                     0     0   ->yellow        Σ (values) = 0
red             0      1     0                     1     0                   Σ (values) = 1
yellow          1      0     0                     0     0                   Σ (values) = 0
blue            0      0     1                     0     1                  Σ (values) = 1

If you do not remove 1st column -> Multicollinearity problem and columns formed are called dumony variables.
dummy variable formation raises to Multicollinearity.

In [49]:
# mention the name of the dataframes and the list of columns on which you want to apply OneHotEncoding
pd.get_dummies(df, columns=['fuel', 'owner'])      # we will apply on brands later

# in this dataframe, we can see    X categories  ->  X columns    (Multicollinearity problem)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

<h2 style="color:blue"> K-1 OneHotEncoding</h2>

In [50]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)          # drop 1st column of fuel and owner

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [209]:
# ❗❗ Important❗❗
#  pandas doesn't remembers which column is placed in which position, if we run it again it may give a different order of columns
#  so we can't implement it in out ML project

<h2 style="color:blue">OneHotEncoding using sklearn</h2>

In [52]:
df.head(3)

    brand  km_driven    fuel         owner  selling_price
0  Maruti     145500  Diesel   First Owner         450000
1   Skoda     120000  Diesel  Second Owner         370000
2   Honda     140000  Petrol   Third Owner         158000

In [62]:
# Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df['selling_price'], test_size=0.25, random_state=0)
X_train.shape, X_test.shape

((6096, 4), (2032, 4))

In [63]:
from sklearn.preprocessing import OneHotEncoder

In [210]:
# ohe = OneHotEncoder()    # create a object of OneHotEncoder

# ohe = OneHotEncoder(drop='first')      #  to drop first column
# ohe = OneHotEncoder(drop='first', sparse_output=False)      
#  it will directly convery into numpy array, no need to use .toarray() later on, else wise it will create a sparse matrix
ohe = OneHotEncoder(drop='first', dtype=np.int32)      #  we can control the datatype of the array formed, bydefault float data type is there

In [212]:
# apply OneHotEncoder to the columns seperately and then merge them with the remaining columns

# train and transform X_train at once
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()       # OneHotEncoder bydefault produces a sparse matrix 

# for X_test we only perform transform (always)
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()         # sparse matrix -> toarray()   convert into a numpy array

X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [86]:
#  now we append "brand" and "km_driven" into the X_train_new

npArray = X_train[['brand', 'km_driven']].values        # data converted to numpy array, 
# we are not applying OneHotEncoding on brands now, as it creates a lot of columns

#  to horizontally stack both numpy arrays npArray and X_Train_new, use np.hstack()
X_train_new = np.hstack((npArray, X_train_new))          # pass both numpy array in a tuple form ()

npArrayTest = X_test[['brand','km_driven']]
X_test_new = np.hstack((npArrayTest, X_test_new))        # all the input array dimensions except for the concatenation axis must match exactly 

X_train_new

array([['Hyundai', 40000, 0, ..., 0, 0, 0],
       ['Mercedes-Benz', 120000, 0, ..., 0, 0, 0],
       ['Hyundai', 80000, 0, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

In [87]:
X_train_new.shape

(6096, 9)

<h2 style="color:blue">OneHotEncoding with Top Categories</h2>

<h3 style="color:brown">Setting Threshold</h3>

In [187]:
brandCount = df['brand'].value_counts()       # store the (brand name and cars count) series in a variable
brandCount                     # brandCount is a pandas series

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [188]:
# we take a threshold of 100. 
# cars count above 100 will have a seperate column while <100 will be clubbed together in 'others' coulmn
threshold = 100

In [189]:
# applying logic, take out the brands name whose threshold is less than 100. 
replaceBrands = brandCount[brandCount <= threshold].index
replaceBrands

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [190]:
df_updated = df.copy()          # avoid changing original dataframe
df_updated['brand'] = df_updated['brand'].replace(replaceBrands, 'Other_Brands')
display(df_updated.sample(5))
df_updated['brand']          # df_updated['brand'] is a pandas Series

           brand  km_driven    fuel         owner  selling_price
3439    Mahindra     120000  Diesel  Second Owner         140000
4546      Maruti      90000  Diesel   First Owner         620000
7292  Volkswagen      69000  Diesel   First Owner         651000
6299      Maruti      57000  Diesel   First Owner         380000
4664        Tata     291977  Diesel   First Owner         500000

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

<h3 style="color:brown">pandas get_dummies()</h3>

In [191]:
pd.get_dummies(df_updated, columns=['fuel','owner','brand'],dtype=np.int32, drop_first=True)

,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,brand_Chevrolet,...,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Other_Brands,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen
0,145500,450000,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,120000,370000,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,140000,158000,0,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,127000,225000,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,120000,130000,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,320000,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8124,119000,135000,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8125,120000,382000,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8126,25000,290000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8127,25000,290000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

<h3 style="color:brown">sklearn OneHotEncoder</h3>

In [192]:
df_updated.sample(5)

           brand  km_driven    fuel        owner  selling_price
7305       Honda       6000  Petrol  First Owner         640000
6833      Maruti      90000  Diesel  First Owner         400000
2145      Maruti      10000  Petrol  First Owner          30000
4104      Maruti      40000  Petrol  First Owner         475000
1970  Volkswagen      34000  Diesel  First Owner         625000

In [193]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(df_updated.iloc[:, :-1], df_updated["selling_price"], test_size=0.25, random_state=0)

X_train.shape, X_test.shape

((6096, 4), (2032, 4))

In [194]:
X_train.sample(5)

       brand  km_driven    fuel        owner
1980  Toyota      20000  Diesel  First Owner
3702    Ford      90000  Petrol  First Owner
523     Tata      42000  Petrol  First Owner
6583  Maruti       5621  Petrol  First Owner
7328   Honda      46000  Diesel  First Owner

In [200]:
# using sklearn library
# updatedBrand.to_frame()        # if updatedBrand -> pandas series, Convert to DataFrame

ohe = OneHotEncoder(drop='first', dtype=np.int32, sparse_output=False)
X_train_encodedCols = ohe.fit_transform(X_train[['brand','fuel','owner']])
X_train_encodedCols.shape

(6096, 19)

In [206]:
# X_train_encodedCols is a numpy array

# ohe.get_feature_names_out()   #  sklearn keeps encoded column names stored in this
encoded_col_names = ohe.get_feature_names_out()  
X_train_encodedCols = pd.DataFrame(X_train_encodedCols, columns=encoded_col_names, index=X_train.index)
# index -> assigns the same row labels as X_train to the encoded DataFrame so pandas can align rows correctly later.
X_train_encodedCols

,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Other_Brands,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
4313,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5178,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
758,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
7117,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2606,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
3264,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1653,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
2607,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
2732,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [207]:
# other_columns = X_train.drop(X_train[['brand','fuel','owner']], axis=1)
# other_columns

# concatenate the rest columns of X_train with X_train_encodedCols 
# axis=1 tells pandas to JOIN DATA SIDE-BY-SIDE (add columns)
X_train_new = pd.concat([X_train['km_driven'], X_train_encodedCols], axis=1)        # Pandas concatenate rows using index values, not row order.
X_train_new

,km_driven,brand_Chevrolet,brand_Ford,brand_Honda,brand_Hyundai,brand_Mahindra,brand_Maruti,brand_Other_Brands,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
4313,40000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5178,120000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
758,80000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
7117,100000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2606,77000,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,70000,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1
3264,100000,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1653,90000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
2607,90000,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
2732,110000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0