<h1 style="color:red">Handling Date and Time Variables </h1>

In [160]:
import pandas as pd 
import numpy as np

In [161]:
date = pd.read_csv('handling_date.csv')
time = pd.read_csv('handling_time.csv')

In [162]:
# In Default when you import any dataset, 'date' and 'time' columns are bydefault are 'object'.
# Make sure to change their data type to datetime64.

<h2 style="color:blue">Handling Date</h2>

In [163]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [164]:
date.info()    # by default 'date' column has 'object' datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [165]:
# Converting to datetime datatype 
date['date'] = pd.to_datetime(date['date'])

In [166]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h3 style='color:brown'>Extract year</h3>

In [167]:
date['date_year'] = date['date'].dt.year         # dt -> datetime

In [168]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

<h3 style='color:brown'>Extract Month and Month Name</h3>

In [169]:
date['date_month'] = date['date'].dt.month
date.head(2)

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8

In [170]:
date['date_month_name'] = date['date'].dt.month_name()   # extract the name of the month
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August

<h3 style='color:brown'>Extract Day</h3>

In [171]:
date['date_day'] = date['date'].dt.day
date.head(3)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23

In [172]:
# day of week 
# 0 -> Monday, 1 -> Tuesday, ......  ,  6 -> Sunday
date['day_of_week'] = date['date'].dt.dayofweek
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,day_of_week
813,2019-06-12,12,25,1,2019,6,June,12,2
841,2019-11-17,5250,3,13,2019,11,November,17,6
691,2019-06-22,1917,0,2,2019,6,June,22,5

In [173]:
# day of week - name 
date['day_name'] = date['date'].dt.day_name()
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,day_of_week,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday

In [174]:
# is weekend 
date['is_weekend'] = np.where(date['day_of_week'].isin([5, 6]), 1, 0)           # check if day_of_week is 5, 6 or not
# date['is_weekend'] = np.where(date['day_name'].isin(['Saturday','Sunday']), 1, 0)
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,day_of_week,day_name,is_weekend
970,2018-11-23,3197,17,15,2018,11,November,23,4,Friday,0
846,2018-09-02,4457,22,80,2018,9,September,2,6,Sunday,1
875,2018-11-01,4495,28,1,2018,11,November,1,3,Thursday,0

<h3 style='color:brown'>Extract Week of the year</h3>

In [175]:
date.drop(columns=['product_id', 'city_id', 'orders'], inplace=True)  # currently no use of these columns

In [176]:
date['week_num'] = date['date'].dt.isocalendar().week          # ISO calendar is explicit and standard
date.head()

,date,date_year,date_month,date_month_name,date_day,day_of_week,day_name,is_weekend,week_num
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [177]:
# Extract quarter of the year
date['quarter'] = date['date'].dt.quarter       #  1 → Jan–Mar
date.head(2)

,date,date_year,date_month,date_month_name,date_day,day_of_week,day_name,is_weekend,week_num,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3

<h3 style='color:brown'>Extract Time elapsed b/w dates</h3>

In [178]:
# extract today's date 
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 1, 24, 12, 21, 20, 823718)

In [179]:
today - date['date']       # pandas series

0     2237 days 12:21:20.823718
1     2719 days 12:21:20.823718
2     2650 days 12:21:20.823718
3     2352 days 12:21:20.823718
4     2575 days 12:21:20.823718
                 ...
995   2665 days 12:21:20.823718
996   2606 days 12:21:20.823718
997   2454 days 12:21:20.823718
998   2519 days 12:21:20.823718
999   2293 days 12:21:20.823718
Name: date, Length: 1000, dtype: timedelta64[ns]

In [180]:
# extract days passed
(today - date['date']).dt.days

0      2237
1      2719
2      2650
3      2352
4      2575
       ...
995    2665
996    2606
997    2454
998    2519
999    2293
Name: date, Length: 1000, dtype: int64

np.timedelta64(value, unit)
👉 Represents a fixed duration of time (a time delta) (not a calendar date) 
    #  ✔ Supported, unambiguous units     : 'W' , 'D', 'h', 'm' , 's', 'ms', 'us', 'ns' 
    # ❌ NOT supported (ambiguous length) : 'M', 'Y'

In [181]:
# Month passed
np.round( (today - date['date']) / np.timedelta64(1,'D') / 30, 0)         # round to '0' decimal places
# Directly assumes: 1 month ≈ 30 days

0      75.0
1      91.0
2      88.0
3      78.0
4      86.0
       ...
995    89.0
996    87.0
997    82.0
998    84.0
999    76.0
Name: date, Length: 1000, dtype: float64

<h2 style="color:blue">Handling Time</h2>

In [182]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [183]:
time.info()         # here also 'date' columns has 'object' datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [184]:
time['date'] = pd.to_datetime(time['date'])      # Converting to datetime datatype

In [186]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

<h3 style='color:brown'>Extracting Time</h3>

In [187]:
time['hour'] = time['date'].dt.hour 
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

<h3 style='color:brown'>Extracting Time part from datetime</h3>

In [189]:
time['time'] = time['date'].dt.time 
time.head(2)

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00

<h3 style='color:brown'>Extracting Time difference</h3>

In [190]:
today - time['date']

0     4423 days 11:31:20.823718
1     4287 days 12:41:20.823718
2     4773 days 12:00:20.823718
3     4075 days 11:50:20.823718
4     4472 days 13:10:20.823718
                 ...
995   5062 days 11:31:20.823718
996   4383 days 13:07:20.823718
997   4848 days 12:44:20.823718
998   4964 days 12:47:20.823718
999   4236 days 12:56:20.823718
Name: date, Length: 1000, dtype: timedelta64[ns]

In [193]:
(today - time['date']) / np.timedelta64(1,'s')    # time difference in seconds

0      3.821887e+08
1      3.704425e+08
2      4.124304e+08
3      3.521226e+08
4      3.864282e+08
           ...
995    4.373983e+08
996    3.787384e+08
997    4.189131e+08
998    4.289356e+08
999    3.660370e+08
Name: date, Length: 1000, dtype: float64

In [195]:
(today - time['date']) / np.timedelta64(1,'m')    # time difference in min

0      6.369811e+06
1      6.174041e+06
2      6.873840e+06
3      5.868710e+06
4      6.440470e+06
           ...
995    7.289971e+06
996    6.312307e+06
997    6.981884e+06
998    7.148927e+06
999    6.100616e+06
Name: date, Length: 1000, dtype: float64

In [196]:
(today - time['date']) / np.timedelta64(1,'h')    # time difference in hours

0      106163.522451
1      102900.689118
2      114564.005784
3       97811.839118
4      107341.172451
           ...
995    121499.522451
996    105205.122451
997    116364.739118
998    119148.789118
999    101676.939118
Name: date, Length: 1000, dtype: float64